require('dotenv').config();

const fs = require('fs');
const http = require('http');
const path = require('path');
const { spawn } = require('child_process');

const ROOT = path.join(__dirname, '..');
const LOG_DIR = path.join(ROOT, 'logs');
const ENV_FILE = path.join(ROOT, '.env');
const ENV_EXAMPLE_FILE = path.join(ROOT, '.env.example');
const LAUNCHER_LOG = path.join(LOG_DIR, 'launcher.log');
const BOT_OUT_LOG = path.join(LOG_DIR, 'bot.out.log');
const BOT_ERR_LOG = path.join(LOG_DIR, 'bot.err.log');
const REFRESH_LOG = path.join(LOG_DIR, 'eva-refresh.out.log');
const PORT = Number(process.env.JARLBOT_LAUNCHER_PORT || 3050);

let botProcess = null;
let refreshProcess = null;
let deployProcess = null;

fs.mkdirSync(LOG_DIR, { recursive: true });

function log(message) {
  const line = `[${new Date().toISOString()}] ${message}\n`;
  fs.appendFileSync(LAUNCHER_LOG, line, 'utf8');
  console.log(line.trim());
}

function parseEnv(content) {
  const result = {};
  for (const line of String(content || '').split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const index = line.indexOf('=');
    if (index === -1) continue;
    result[line.slice(0, index).trim()] = line.slice(index + 1).trim();
  }
  return result;
}

function readEnv() {
  const source = fs.existsSync(ENV_FILE) ? ENV_FILE : ENV_EXAMPLE_FILE;
  return parseEnv(fs.existsSync(source) ? fs.readFileSync(source, 'utf8') : '');
}

function serializeEnv(values) {
  const order = [
    'DISCORD_TOKEN',
    'CLIENT_ID',
    'GUILD_ID',
    'CATEGORIE_DEFIS_ID',
    'EVA_ACCESS_TOKEN',
    'EVA_COMPETITIVE_API_BASE_URL',
    'EVA_GRAPHQL_URL',
    'EVA_LOCAL_LEAGUES_CIRCUIT_ID',
    'EVA_MAJOR_TOURNAMENT_IDS',
    'EVA_V2_CACHE_TTL_MS',
    'EVA_V2_MIN_INTERVAL_MS',
    'EVA_V2_HTTP_TIMEOUT_MS',
    'EVA_V2_TEAM_MEMBER_REFRESH_LIMIT',
    'EVA_V2_TEAM_MEMBER_FULL_REFRESH_LIMIT',
    'EVA_V2_MAJOR_PLAYER_REFRESH_LIMIT',
    'EVA_V2_MAJOR_PLAYER_FULL_REFRESH_LIMIT',
    'EVA_V2_COMMAND_PLAYER_HYDRATE_LIMIT',
  ];
  const lines = [
    '# JarlBot local configuration',
    '# Generated by the local launcher. Keep DISCORD_TOKEN secret.',
  ];
  for (const key of order) {
    if (values[key] != null && values[key] !== '') lines.push(`${key}=${values[key]}`);
  }
  for (const [key, value] of Object.entries(values)) {
    if (!order.includes(key) && value != null && value !== '') lines.push(`${key}=${value}`);
  }
  return `${lines.join('\n')}\n`;
}

function writeEnv(updates) {
  const current = readEnv();
  const next = { ...current };
  for (const [key, value] of Object.entries(updates)) {
    if (value !== undefined && value !== null) next[key] = String(value).trim();
  }
  fs.writeFileSync(ENV_FILE, serializeEnv(next), 'utf8');
  Object.assign(process.env, next);
  log('Configuration .env mise a jour via le launcher.');
  return next;
}

function json(res, payload, statusCode = 200) {
  const body = JSON.stringify(payload);
  res.writeHead(statusCode, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body),
  });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', chunk => {
      data += chunk;
      if (data.length > 1_000_000) {
        req.destroy();
        reject(new Error('Payload trop volumineux.'));
      }
    });
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch (err) {
        reject(err);
      }
    });
  });
}

function mask(value) {
  if (!value) return '';
  return `${String(value).slice(0, 4)}...${String(value).slice(-4)}`;
}

function buildInviteUrl(clientId) {
  if (!clientId) return '';
  const permissions = [
    1n << 4n,  // ManageChannels
    1n << 6n,  // AddReactions
    1n << 10n, // ViewChannel
    1n << 11n, // SendMessages
    1n << 16n, // ReadMessageHistory
    1n << 17n, // MentionEveryone
    1n << 28n, // ManageRoles
    1n << 33n, // ManageEvents
  ].reduce((sum, bit) => sum + bit, 0n);
  const params = new URLSearchParams({
    client_id: clientId,
    permissions: permissions.toString(),
    scope: 'bot applications.commands',
  });
  return `https://discord.com/oauth2/authorize?${params.toString()}`;
}

function getDbStatus() {
  try {
    delete require.cache[require.resolve('../utils/eva-v2')];
    const { getEvaV2Status } = require('../utils/eva-v2');
    return getEvaV2Status();
  } catch (err) {
    return { error: err.message };
  }
}

function tail(file, maxLines = 160) {
  if (!fs.existsSync(file)) return '';
  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
  return lines.slice(Math.max(0, lines.length - maxLines)).join('\n');
}

function startBot() {
  if (botProcess && !botProcess.killed) return { started: false, message: 'Bot deja lance par le launcher.' };
  const out = fs.openSync(BOT_OUT_LOG, 'a');
  const err = fs.openSync(BOT_ERR_LOG, 'a');
  botProcess = spawn(process.execPath, ['index.js'], {
    cwd: ROOT,
    detached: false,
    stdio: ['ignore', out, err],
    env: { ...process.env, ...readEnv() },
  });
  botProcess.on('exit', code => {
    log(`Bot arrete avec code ${code}.`);
    botProcess = null;
  });
  log(`Bot lance (pid ${botProcess.pid}).`);
  return { started: true, pid: botProcess.pid };
}

function stopBot() {
  if (!botProcess || botProcess.killed) return { stopped: false, message: 'Aucun bot lance par le launcher.' };
  const pid = botProcess.pid;
  botProcess.kill();
  log(`Arret demande du bot (pid ${pid}).`);
  return { stopped: true, pid };
}

function startRefresh(mode) {
  if (refreshProcess && !refreshProcess.killed) return { started: false, message: 'Refresh deja en cours.' };
  const args = ['scripts/eva-refresh.js'];
  if (mode === 'reset') args.push('--reset', '--full');
  if (mode === 'full') args.push('--full');
  const out = fs.openSync(REFRESH_LOG, 'a');
  refreshProcess = spawn(process.execPath, args, {
    cwd: ROOT,
    detached: false,
    stdio: ['ignore', out, out],
    env: { ...process.env, ...readEnv() },
  });
  refreshProcess.on('exit', code => {
    log(`Refresh EVA termine avec code ${code}.`);
    refreshProcess = null;
  });
  log(`Refresh EVA lance (${mode || 'normal'}, pid ${refreshProcess.pid}).`);
  return { started: true, pid: refreshProcess.pid };
}

function runExport() {
  return new Promise(resolve => {
    const child = spawn(process.execPath, ['scripts/export-portable.js'], {
      cwd: ROOT,
      env: { ...process.env, ...readEnv() },
    });
    let output = '';
    child.stdout.on('data', chunk => { output += chunk.toString(); });
    child.stderr.on('data', chunk => { output += chunk.toString(); });
    child.on('exit', code => {
      log(`Export portable termine avec code ${code}.`);
      resolve({ code, output });
    });
  });
}

function openBrowser(url) {
  const command = process.platform === 'win32'
    ? ['cmd', ['/c', 'start', '', url]]
    : process.platform === 'darwin'
      ? ['open', [url]]
      : ['xdg-open', [url]];
  spawn(command[0], command[1], { detached: true, stdio: 'ignore' }).unref();
}

const html = `<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>JarlBot Launcher</title>
  <style>
    :root {
      --bg: #f4efe5;
      --ink: #1f2523;
      --muted: #68736f;
      --panel: rgba(255,255,255,.76);
      --line: rgba(31,37,35,.14);
      --brand: #d96f32;
      --brand-dark: #9f411c;
      --ok: #267d52;
      --warn: #a45f13;
      --bad: #b93737;
      --shadow: 0 22px 70px rgba(31,37,35,.15);
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: ui-rounded, "Segoe UI", "Trebuchet MS", sans-serif;
      color: var(--ink);
      background:
        radial-gradient(circle at top left, rgba(217,111,50,.25), transparent 34rem),
        linear-gradient(135deg, #f7efe0 0%, #e6f0ea 54%, #f8f6ef 100%);
      min-height: 100vh;
    }
    header {
      padding: 44px min(6vw, 72px) 20px;
      display: flex;
      justify-content: space-between;
      gap: 24px;
      align-items: flex-end;
    }
    h1 { font-size: clamp(2.2rem, 5vw, 4.6rem); line-height: .9; margin: 0; letter-spacing: -.06em; }
    .subtitle { color: var(--muted); max-width: 680px; font-size: 1.05rem; }
    .pill { border: 1px solid var(--line); border-radius: 999px; padding: 10px 14px; background: var(--panel); }
    main { padding: 16px min(6vw, 72px) 56px; }
    .grid { display: grid; grid-template-columns: minmax(320px, 1fr) minmax(320px, .9fr); gap: 18px; }
    .card {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 28px;
      box-shadow: var(--shadow);
      padding: 24px;
      backdrop-filter: blur(18px);
    }
    .wide { grid-column: 1 / -1; }
    h2 { margin: 0 0 14px; font-size: 1.3rem; }
    label { display: block; font-weight: 700; margin: 12px 0 6px; }
    input, textarea, select {
      width: 100%;
      border: 1px solid var(--line);
      background: rgba(255,255,255,.82);
      border-radius: 14px;
      padding: 12px 13px;
      font: inherit;
      color: var(--ink);
    }
    input:focus, textarea:focus, select:focus { outline: 2px solid rgba(217,111,50,.35); border-color: var(--brand); }
    button, .button {
      border: 0;
      border-radius: 16px;
      padding: 12px 15px;
      background: var(--ink);
      color: white;
      font-weight: 800;
      cursor: pointer;
      text-decoration: none;
      display: inline-flex;
      align-items: center;
      gap: 8px;
      justify-content: center;
    }
    button.secondary { background: rgba(31,37,35,.09); color: var(--ink); }
    button.brand { background: var(--brand); }
    button.danger { background: var(--bad); }
    .actions { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 16px; }
    .status { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }
    .stat { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,.55); }
    .stat b { display: block; font-size: 1.6rem; }
    .ok { color: var(--ok); } .warn { color: var(--warn); } .bad { color: var(--bad); }
    pre {
      white-space: pre-wrap;
      overflow: auto;
      max-height: 390px;
      background: #18201d;
      color: #e7f2ed;
      padding: 16px;
      border-radius: 18px;
      font-size: .88rem;
    }
    .hint { color: var(--muted); font-size: .92rem; }
    @media (max-width: 900px) { header { display: block; } .grid { grid-template-columns: 1fr; } .status { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>JarlBot<br>Launcher</h1>
      <p class="subtitle">Console locale pour configurer Discord, inviter le bot, lancer les refreshs EVA et surveiller les logs sans ouvrir le capot moteur.</p>
    </div>
    <div class="pill" id="processState">Chargement...</div>
  </header>
  <main class="grid">
    <section class="card">
      <h2>1. Configuration Discord</h2>
      <p class="hint">Ces valeurs sont sauvegardees dans <code>.env</code>. Le token n'est jamais affiche une fois enregistre.</p>
      <label>Discord Bot Token</label>
      <input id="DISCORD_TOKEN" type="password" placeholder="Colle le token Discord ici" autocomplete="off" />
      <label>Client ID / Application ID</label>
      <input id="CLIENT_ID" placeholder="Ex: 123456789012345678" />
      <label>Guild ID / Serveur Discord</label>
      <input id="GUILD_ID" placeholder="Ex: 123456789012345678" />
      <label>Categorie des salons matchs</label>
      <input id="CATEGORIE_DEFIS_ID" placeholder="ID de la categorie Discord" />
      <label>Token EVA optionnel</label>
      <input id="EVA_ACCESS_TOKEN" type="password" placeholder="Optionnel, pour GraphQL public" autocomplete="off" />
      <div class="actions">
        <button class="brand" onclick="saveConfig()">Sauvegarder</button>
        <button class="secondary" onclick="copyInvite()">Copier lien invitation</button>
        <a class="button" id="inviteLink" href="#" target="_blank">Ouvrir invitation</a>
      </div>
    </section>

    <section class="card">
      <h2>2. Pilotage</h2>
      <div class="status" id="dbStats"></div>
      <div class="actions">
        <button class="brand" onclick="startBot()">Lancer le bot</button>
        <button class="danger" onclick="stopBot()">Arreter le bot</button>
        <button class="secondary" onclick="deploy()">Enregistrer slash commands</button>
      </div>
      <div class="actions">
        <button onclick="refresh('normal')">Refresh EVA</button>
        <button onclick="refresh('full')">Refresh complet</button>
        <button class="danger" onclick="refresh('reset')">Reset + repeuplement</button>
      </div>
      <div class="actions">
        <button class="secondary" onclick="exportPortable()">Exporter version portable</button>
      </div>
      <p class="hint" id="lastAction">Pret.</p>
    </section>

    <section class="card wide">
      <h2>Logs</h2>
      <div class="actions">
        <select id="logKind" onchange="loadLogs()">
          <option value="bot">Bot</option>
          <option value="error">Erreurs bot</option>
          <option value="refresh">Refresh EVA</option>
          <option value="launcher">Launcher</option>
        </select>
        <button class="secondary" onclick="loadLogs()">Rafraichir logs</button>
      </div>
      <pre id="logs"></pre>
    </section>
  </main>
  <script>
    let inviteUrl = '';
    async function api(path, options = {}) {
      const res = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Erreur inconnue');
      return data;
    }
    function setLast(text, type = '') {
      const el = document.getElementById('lastAction');
      el.className = 'hint ' + type;
      el.textContent = text;
    }
    async function loadStatus() {
      const status = await api('/api/status');
      document.getElementById('processState').textContent =
        'Bot: ' + (status.botRunning ? 'lance' : 'arrete') + ' | Refresh: ' + (status.refreshRunning ? 'en cours' : 'idle');
      for (const key of ['CLIENT_ID', 'GUILD_ID', 'CATEGORIE_DEFIS_ID']) document.getElementById(key).value = status.env[key] || '';
      document.getElementById('DISCORD_TOKEN').placeholder = status.env.DISCORD_TOKEN ? 'Token deja configure (' + status.env.DISCORD_TOKEN + ')' : 'Colle le token Discord ici';
      document.getElementById('EVA_ACCESS_TOKEN').placeholder = status.env.EVA_ACCESS_TOKEN ? 'Token EVA configure (' + status.env.EVA_ACCESS_TOKEN + ')' : 'Optionnel, pour GraphQL public';
      inviteUrl = status.inviteUrl || '';
      document.getElementById('inviteLink').href = inviteUrl || '#';
      const db = status.db || {};
      document.getElementById('dbStats').innerHTML = ['teams','players','rankings','rankingItems','majorTeams','locations'].map(k =>
        '<div class="stat"><span>' + k + '</span><b>' + (db[k] ?? '-') + '</b></div>'
      ).join('');
    }
    async function saveConfig() {
      const payload = {};
      for (const key of ['DISCORD_TOKEN','CLIENT_ID','GUILD_ID','CATEGORIE_DEFIS_ID','EVA_ACCESS_TOKEN']) {
        const value = document.getElementById(key).value.trim();
        if (value) payload[key] = value;
      }
      await api('/api/config', { method: 'POST', body: JSON.stringify(payload) });
      setLast('Configuration sauvegardee.', 'ok');
      await loadStatus();
    }
    async function copyInvite() {
      if (!inviteUrl) return setLast('Renseigne le Client ID avant de copier le lien.', 'warn');
      await navigator.clipboard.writeText(inviteUrl);
      setLast('Lien invitation copie.', 'ok');
    }
    async function startBot() { const r = await api('/api/bot/start', { method: 'POST' }); setLast(r.message || 'Bot lance.', 'ok'); await loadStatus(); }
    async function stopBot() { const r = await api('/api/bot/stop', { method: 'POST' }); setLast(r.message || 'Arret demande.', 'warn'); await loadStatus(); }
    async function deploy() { const r = await api('/api/deploy', { method: 'POST' }); setLast(r.message || 'Deploy lance.', 'ok'); }
    async function refresh(mode) { const r = await api('/api/refresh', { method: 'POST', body: JSON.stringify({ mode }) }); setLast(r.message || 'Refresh lance.', 'ok'); await loadStatus(); }
    async function exportPortable() { const r = await api('/api/export', { method: 'POST' }); setLast('Export termine: ' + r.output, r.code === 0 ? 'ok' : 'bad'); }
    async function loadLogs() {
      const kind = document.getElementById('logKind').value;
      const data = await api('/api/logs?kind=' + encodeURIComponent(kind));
      document.getElementById('logs').textContent = data.logs || '(aucun log)';
    }
    loadStatus().catch(err => setLast(err.message, 'bad'));
    loadLogs();
    setInterval(loadStatus, 5000);
    setInterval(loadLogs, 7000);
  </script>
</body>
</html>`;

async function handle(req, res) {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    if (req.method === 'GET' && url.pathname === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(html);
      return;
    }
    if (req.method === 'GET' && url.pathname === '/api/status') {
      const env = readEnv();
      json(res, {
        env: {
          CLIENT_ID: env.CLIENT_ID || '',
          GUILD_ID: env.GUILD_ID || '',
          CATEGORIE_DEFIS_ID: env.CATEGORIE_DEFIS_ID || '',
          DISCORD_TOKEN: mask(env.DISCORD_TOKEN),
          EVA_ACCESS_TOKEN: mask(env.EVA_ACCESS_TOKEN),
        },
        inviteUrl: buildInviteUrl(env.CLIENT_ID),
        botRunning: Boolean(botProcess && !botProcess.killed),
        refreshRunning: Boolean(refreshProcess && !refreshProcess.killed),
        db: getDbStatus(),
      });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/config') {
      const body = await readBody(req);
      writeEnv(body);
      json(res, { ok: true });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/bot/start') {
      json(res, startBot());
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/bot/stop') {
      json(res, stopBot());
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/refresh') {
      const body = await readBody(req);
      const result = startRefresh(body.mode || 'normal');
      json(res, { ...result, message: result.started ? `Refresh ${body.mode || 'normal'} lance.` : result.message });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/deploy') {
      if (deployProcess && !deployProcess.killed) {
        json(res, { ok: false, message: 'Enregistrement deja en cours.' });
        return;
      }
      const out = fs.openSync(LAUNCHER_LOG, 'a');
      deployProcess = spawn(process.execPath, ['deploy-commands.js'], {
        cwd: ROOT,
        stdio: ['ignore', out, out],
        env: { ...process.env, ...readEnv() },
      });
      deployProcess.on('exit', code => {
        log(`Deploy slash commands termine avec code ${code}.`);
        deployProcess = null;
      });
      log(`Deploy slash commands lance (pid ${deployProcess.pid}).`);
      json(res, { ok: true, message: 'Enregistrement des commandes lance.' });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/export') {
      const result = await runExport();
      json(res, result, result.code === 0 ? 200 : 500);
      return;
    }
    if (req.method === 'GET' && url.pathname === '/api/logs') {
      const kind = url.searchParams.get('kind') || 'bot';
      const file = kind === 'error' ? BOT_ERR_LOG : kind === 'refresh' ? REFRESH_LOG : kind === 'launcher' ? LAUNCHER_LOG : BOT_OUT_LOG;
      json(res, { logs: tail(file) });
      return;
    }
    json(res, { error: 'Route introuvable.' }, 404);
  } catch (err) {
    log(`Erreur launcher: ${err.stack || err.message}`);
    json(res, { error: err.message }, 500);
  }
}

const server = http.createServer((req, res) => {
  handle(req, res);
});

server.listen(PORT, () => {
  const url = `http://localhost:${PORT}`;
  log(`Launcher disponible sur ${url}`);
  if (process.env.JARLBOT_LAUNCHER_NO_OPEN !== '1') openBrowser(url);
});
