require('dotenv').config();

const fs = require('fs');
const http = require('http');
const path = require('path');
const { spawn } = require('child_process');

const ROOT = path.join(__dirname, '..');
const LOG_DIR = path.join(ROOT, 'logs');
const ENV_FILE = path.join(ROOT, '.env');
const ENV_EXAMPLE_FILE = path.join(ROOT, '.env.example');
const LAUNCHER_LOG = path.join(LOG_DIR, 'launcher.log');
const BOT_OUT_LOG = path.join(LOG_DIR, 'bot.out.log');
const BOT_ERR_LOG = path.join(LOG_DIR, 'bot.err.log');
const REFRESH_LOG = path.join(LOG_DIR, 'eva-refresh.out.log');
const PORT = Number(process.env.JARLBOT_LAUNCHER_PORT || 3050);

let botProcess = null;
let refreshProcess = null;
let deployProcess = null;

fs.mkdirSync(LOG_DIR, { recursive: true });

function log(message) {
  const line = `[${new Date().toISOString()}] ${message}\n`;
  fs.appendFileSync(LAUNCHER_LOG, line, 'utf8');
  console.log(line.trim());
}

function parseEnv(content) {
  const result = {};
  for (const line of String(content || '').split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const index = line.indexOf('=');
    if (index === -1) continue;
    result[line.slice(0, index).trim()] = line.slice(index + 1).trim();
  }
  return result;
}

function readEnv() {
  const source = fs.existsSync(ENV_FILE) ? ENV_FILE : ENV_EXAMPLE_FILE;
  return parseEnv(fs.existsSync(source) ? fs.readFileSync(source, 'utf8') : '');
}

function serializeEnv(values) {
  const order = [
    'DISCORD_TOKEN',
    'CLIENT_ID',
    'GUILD_ID',
    'CATEGORIE_DEFIS_ID',
    'JARLBOT_MODE',
    'EVA_COMPETITIVE_API_BASE_URL',
    'EVA_GRAPHQL_URL',
    'EVA_LOCAL_LEAGUES_CIRCUIT_ID',
    'EVA_MAJOR_TOURNAMENT_IDS',
    'EVA_V2_CACHE_TTL_MS',
    'EVA_V2_MIN_INTERVAL_MS',
    'EVA_V2_HTTP_TIMEOUT_MS',
    'EVA_V2_TEAM_MEMBER_REFRESH_LIMIT',
    'EVA_V2_TEAM_MEMBER_FULL_REFRESH_LIMIT',
    'EVA_V2_MAJOR_PLAYER_REFRESH_LIMIT',
    'EVA_V2_MAJOR_PLAYER_FULL_REFRESH_LIMIT',
    'EVA_V2_COMMAND_PLAYER_HYDRATE_LIMIT',
  ];
  const lines = [
    '# JarlBot local configuration',
    '# Generated by the local launcher. Keep DISCORD_TOKEN secret.',
  ];
  for (const key of order) {
    if (values[key] != null && values[key] !== '') lines.push(`${key}=${values[key]}`);
  }
  for (const [key, value] of Object.entries(values)) {
    if (!order.includes(key) && value != null && value !== '') lines.push(`${key}=${value}`);
  }
  return `${lines.join('\n')}\n`;
}

function writeEnv(updates) {
  const current = readEnv();
  const next = { ...current };
  for (const [key, value] of Object.entries(updates)) {
    if (value !== undefined && value !== null) next[key] = String(value).trim();
  }
  fs.writeFileSync(ENV_FILE, serializeEnv(next), 'utf8');
  Object.assign(process.env, next);
  log('Configuration .env mise a jour via le launcher.');
  return next;
}

function json(res, payload, statusCode = 200) {
  const body = JSON.stringify(payload);
  res.writeHead(statusCode, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body),
  });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', chunk => {
      data += chunk;
      if (data.length > 1_000_000) {
        req.destroy();
        reject(new Error('Payload trop volumineux.'));
      }
    });
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {});
      } catch (err) {
        reject(err);
      }
    });
  });
}

function mask(value) {
  if (!value) return '';
  return `${String(value).slice(0, 4)}...${String(value).slice(-4)}`;
}

// Note: invite link generation removed from frontend by design.

function getDbStatus() {
  try {
    delete require.cache[require.resolve('../utils/eva-v2')];
    const { getEvaV2Status } = require('../utils/eva-v2');
    return getEvaV2Status();
  } catch (err) {
    return { error: err.message };
  }
}

function tail(file, maxLines = 160) {
  if (!fs.existsSync(file)) return '';
  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
  return lines.slice(Math.max(0, lines.length - maxLines)).join('\n');
}

function deploySlashCommands() {
  if (deployProcess && !deployProcess.killed) return;
  const deployOut = fs.openSync(LAUNCHER_LOG, 'a');
  deployProcess = spawn(process.execPath, ['deploy-commands.js'], {
    cwd: ROOT,
    stdio: ['ignore', deployOut, deployOut],
    env: { ...process.env, ...readEnv() },
  });
  deployProcess.on('exit', code => {
    log(`Deploy slash commands termine avec code ${code}.`);
    deployProcess = null;
  });
  log(`Deploy slash commands lance (pid ${deployProcess.pid}).`);
}

function spawnBotProcess() {
  const out = fs.openSync(BOT_OUT_LOG, 'a');
  const err = fs.openSync(BOT_ERR_LOG, 'a');
  const child = spawn(process.execPath, ['index.js'], {
    cwd: ROOT,
    detached: false,
    stdio: ['ignore', out, err],
    env: { ...process.env, ...readEnv() },
  });
  botProcess = child;
  child.on('exit', code => {
    log(`Bot arrete avec code ${code}.`);
    if (botProcess === child) botProcess = null;
  });
  log(`Bot lance (pid ${botProcess.pid}).`);
  return child;
}

function startBot() {
  let restarted = false;
  if (botProcess && !botProcess.killed) {
    const oldPid = botProcess.pid;
    botProcess.kill();
    restarted = true;
    log(`Redemarrage du bot demande pour appliquer la configuration (ancien pid ${oldPid}).`);
  }
  const child = spawnBotProcess();
  deploySlashCommands();
  return {
    started: true,
    restarted,
    pid: child.pid,
    message: restarted ? 'Bot redemarre + slash commands enregistrees.' : 'Bot lance + slash commands enregistrees.',
  };
}

function stopBot() {
  if (!botProcess || botProcess.killed) return { stopped: false, message: 'Aucun bot lance par le launcher.' };
  const pid = botProcess.pid;
  botProcess.kill();
  log(`Arret demande du bot (pid ${pid}).`);
  return { stopped: true, pid };
}

function startRefresh(mode) {
  if (refreshProcess && !refreshProcess.killed) return { started: false, message: 'Refresh deja en cours.' };
  const args = ['scripts/eva-refresh.js'];
  if (mode === 'reset') args.push('--reset', '--full');
  if (mode === 'full') args.push('--full');
  const out = fs.openSync(REFRESH_LOG, 'a');
  refreshProcess = spawn(process.execPath, args, {
    cwd: ROOT,
    detached: false,
    stdio: ['ignore', out, out],
    env: { ...process.env, ...readEnv() },
  });
  refreshProcess.on('exit', code => {
    log(`Refresh EVA termine avec code ${code}.`);
    refreshProcess = null;
  });
  log(`Refresh EVA lance (${mode || 'normal'}, pid ${refreshProcess.pid}).`);
  return { started: true, pid: refreshProcess.pid };
}

function runExport() {
  return new Promise(resolve => {
    const child = spawn(process.execPath, ['scripts/export-portable.js'], {
      cwd: ROOT,
      env: { ...process.env, ...readEnv() },
    });
    let output = '';
    child.stdout.on('data', chunk => { output += chunk.toString(); });
    child.stderr.on('data', chunk => { output += chunk.toString(); });
    child.on('exit', code => {
      log(`Export portable termine avec code ${code}.`);
      resolve({ code, output });
    });
  });
}

function openBrowser(url) {
  const command = process.platform === 'win32'
    ? ['cmd', ['/c', 'start', '', url]]
    : process.platform === 'darwin'
      ? ['open', [url]]
      : ['xdg-open', [url]];
  spawn(command[0], command[1], { detached: true, stdio: 'ignore' }).unref();
}

const html = `<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>JarlBot Launcher</title>
  <style>
    :root {
      --bg: #0c0d12;
      --bg-2: #121420;
      --panel: rgba(19, 20, 30, .86);
      --panel-strong: rgba(25, 26, 38, .96);
      --ink: #f2f4ff;
      --muted: #9aa0b9;
      --line: rgba(181, 111, 255, .16);
      --brand: #b84dff;
      --brand-2: #7a31ff;
      --glow: rgba(184, 77, 255, .45);
      --ok: #43d39e;
      --warn: #ffb020;
      --bad: #ff5f7d;
      --shadow: 0 24px 90px rgba(0, 0, 0, .45);
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--ink);
      background:
        radial-gradient(circle at top left, rgba(184,77,255,.24), transparent 26rem),
        radial-gradient(circle at top right, rgba(122,49,255,.14), transparent 22rem),
        linear-gradient(135deg, #090a0f 0%, #0f1220 45%, #11131b 100%);
      min-height: 100vh;
      letter-spacing: .01em;
      }
    .subtitle {
      color: var(--muted);
      max-width: 760px;
      font-size: 1.02rem;
      margin-top: 14px;
    }
    .pill {
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 10px 14px;
      background: rgba(18, 20, 32, .82);
      box-shadow: 0 0 0 1px rgba(255,255,255,.02) inset, 0 0 32px rgba(184,77,255,.08);
    }
    .status-pill {
      display: inline-flex;
      align-items: center;
      gap: 10px;
      min-width: 170px;
    }
    .status-dot {
      width: 10px;
      height: 10px;
      border-radius: 999px;
      background: var(--muted);
      box-shadow: 0 0 0 0 rgba(184,77,255,.0);
      flex: 0 0 auto;
    }
    .status-pill.online .status-dot {
      background: var(--ok);
      box-shadow: 0 0 0 6px rgba(67,211,158,.12);
    }
    .status-pill.offline .status-dot {
      background: var(--bad);
      box-shadow: 0 0 0 6px rgba(255,95,125,.12);
    }
    .status-copy {
      display: flex;
      flex-direction: column;
      line-height: 1.1;
    }
    .status-copy strong {
      font-size: .95rem;
      letter-spacing: -.02em;
    }
    .status-copy span {
      color: var(--muted);
      font-size: .82rem;
      margin-top: 2px;
    }
    main { padding: 10px min(6vw, 72px) 56px; }
    .grid { display: grid; grid-template-columns: minmax(320px, 1fr); gap: 18px; }
    .card {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 30px;
      box-shadow: var(--shadow);
      padding: 26px;
      backdrop-filter: blur(20px);
      position: relative;
      overflow: hidden;
    }
    .card::before {
      content: '';
      position: absolute;
      inset: 0;
      background: linear-gradient(135deg, rgba(184,77,255,.12), transparent 32%, rgba(122,49,255,.08));
      pointer-events: none;
    }
    .card > * { position: relative; z-index: 1; }
    h2 {
      margin: 0 0 10px;
      font-size: 1.2rem;
      letter-spacing: -.03em;
    }
    .section-note {
      margin: 0 0 18px;
      color: var(--muted);
      font-size: .95rem;
    }
    label { display: block; font-weight: 700; margin: 12px 0 6px; }
    input, textarea, select {
      width: 100%;
      border: 1px solid rgba(184,77,255,.16);
      background: rgba(10, 11, 16, .72);
      border-radius: 14px;
      padding: 12px 13px;
      font: inherit;
      color: var(--ink);
    }
    input::placeholder { color: #7880a1; }
    input:focus, textarea:focus, select:focus {
      outline: 2px solid rgba(184,77,255,.28);
      border-color: rgba(184,77,255,.75);
      box-shadow: 0 0 0 4px rgba(184,77,255,.08);
    }
    button, .button {
      border: 0;
      border-radius: 16px;
      padding: 12px 15px;
      background: rgba(255,255,255,.08);
      color: var(--ink);
      font-weight: 800;
      cursor: pointer;
      text-decoration: none;
      display: inline-flex;
      align-items: center;
      gap: 8px;
      justify-content: center;
      transition: transform .15s ease, box-shadow .15s ease, background .15s ease, border-color .15s ease;
      border: 1px solid rgba(255,255,255,.08);
    }
    button:hover, .button:hover { transform: translateY(-1px); box-shadow: 0 12px 30px rgba(0,0,0,.24); }
    button.secondary, .button.secondary { background: rgba(255,255,255,.06); }
    button.brand, .button.brand {
      background: linear-gradient(135deg, var(--brand), var(--brand-2));
      box-shadow: 0 10px 30px rgba(184,77,255,.24);
    }
    button.danger { background: linear-gradient(135deg, #ff5f7d, #cf3f76); }
    .actions { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 16px; }
    .ok { color: var(--ok); } .warn { color: var(--warn); } .bad { color: var(--bad); }
    .hint { color: var(--muted); font-size: .92rem; }
    .statusline {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      margin-top: 14px;
    }
    .chip {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      border-radius: 999px;
      padding: 10px 14px;
      background: rgba(255,255,255,.05);
      border: 1px solid rgba(184,77,255,.16);
      color: var(--ink);
    }
    .chip b { font-size: .98rem; }
    .launch-band {
      display: flex;
      align-items: flex-end;
      gap: 10px;
      margin-top: 18px;
      padding: 14px;
      border-radius: 20px;
      background: linear-gradient(135deg, rgba(184,77,255,.14), rgba(122,49,255,.08));
      border: 1px solid rgba(184,77,255,.18);
    }
    .launch-band strong { display:block; }
    .launch-band span { color: var(--muted); font-size: .92rem; }
    .invite-line {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      margin-left: auto;
      justify-content: flex-end;
    }
    .footer-panel {
      margin-top: 18px;
      padding: 18px;
      border-radius: 22px;
      background: rgba(255,255,255,.04);
      border: 1px solid rgba(184,77,255,.14);
    }
    .footer-head {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: center;
      margin-bottom: 12px;
      flex-wrap: wrap;
    }
    .logs-bar {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      align-items: center;
    }
    pre {
      white-space: pre-wrap;
      overflow: auto;
      max-height: 340px;
      background: #0b0d14;
      color: #e8eaff;
      padding: 16px;
      border-radius: 18px;
      font-size: .88rem;
      border: 1px solid rgba(184,77,255,.12);
      margin: 0;
    }
    @media (max-width: 900px) { header { display: block; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>JarlBot<br>Launcher</h1>
    </div>
    <div class="pill status-pill offline" id="processState">
      <span class="status-dot" aria-hidden="true"></span>
      <span class="status-copy">
        <strong>Chargement...</strong>
        <span>Etat du bot</span>
      </span>
    </div>
  </header>
  <main class="grid">
    <section class="card">
      <h2>Configuration Discord</h2>
      <p class="section-note">Les valeurs ci-dessous sont enregistrées dans <code>.env</code>. Le token ne s'affiche jamais une fois sauvé.</p>
      <label>Discord Bot Token</label>
      <input id="DISCORD_TOKEN" type="password" placeholder="Colle le token Discord ici" autocomplete="off" />
      <label>Client ID / Application ID</label>
      <input id="CLIENT_ID" placeholder="Ex: 123456789012345678" />
      <label>Guild ID / Serveur Discord</label>
      <input id="GUILD_ID" placeholder="Ex: 123456789012345678" />
      <label>Categorie des salons matchs</label>
      <input id="CATEGORIE_DEFIS_ID" placeholder="ID de la categorie Discord" />
      <label>Mode de fonctionnement</label>
      <select id="JARLBOT_MODE">
        <option value="prod">Production - validation par role adverse</option>
        <option value="test">Test - une personne valide tout</option>
      </select>
      <p class="section-note" style="margin-top:8px">Le mode test sert a verifier les commandes, salons, evenements, suppressions et rappels sans mobiliser plusieurs joueurs.</p>
      <div class="launch-band">
        <div>
          <strong>Lancer le bot</strong>
          <span>Le lancement enregistre aussi les slash commands.</span>
        </div>
              <div class="invite-line" style="margin-left:auto">
                <button class="brand" onclick="saveAndStart()">Sauvegarder et lancer</button>
                <button class="danger" onclick="stopLauncher()">Arrêter</button>
              </div>
      </div>
    </section>
    <section class="footer-panel">
      <div class="footer-head">
        <div>
          <h2>Logs disponibles</h2>
          <p class="section-note" style="margin:0">Les derniers journaux utiles du bot et du launcher.</p>
        </div>
        <div class="logs-bar">
          <select id="logKind" onchange="loadLogs()">
            <option value="bot">Bot</option>
            <option value="error">Erreurs bot</option>
            <option value="refresh">Refresh EVA</option>
            <option value="launcher">Launcher</option>
          </select>
          <button class="secondary" onclick="loadLogs()">Rafraichir logs</button>
        </div>
      </div>
      <div class="hint" id="lastAction">Pret.</div>
      <pre id="logs"></pre>
    </section>
  </main>
  <script>
    let inviteUrl = '';
    async function api(path, options = {}) {
      const res = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Erreur inconnue');
      return data;
    }
    function setLast(text, type = '') {
      const el = document.getElementById('lastAction');
      if (!el) return;
      el.className = 'hint ' + type;
      el.textContent = text;
    }
    async function loadStatus() {
      const status = await api('/api/status');
      const pill = document.getElementById('processState');
      pill.classList.toggle('online', !!status.botRunning);
      pill.classList.toggle('offline', !status.botRunning);
      pill.querySelector('strong').textContent = status.botRunning ? 'Bot en ligne' : 'Bot arrete';
      pill.querySelector('span.status-copy span').textContent = status.botRunning ? 'Pret a recevoir des commandes' : 'Prend quelques secondes au demarrage';
      for (const key of ['CLIENT_ID', 'GUILD_ID', 'CATEGORIE_DEFIS_ID']) document.getElementById(key).value = status.env[key] || '';
      document.getElementById('JARLBOT_MODE').value = status.env.JARLBOT_MODE || 'prod';
      document.getElementById('DISCORD_TOKEN').placeholder = status.env.DISCORD_TOKEN ? 'Token deja configure (' + status.env.DISCORD_TOKEN + ')' : 'Colle le token Discord ici';
      // invite links are not displayed in the launcher UI by design
    }
    async function loadLogs() {
      const kind = document.getElementById('logKind').value;
      const data = await api('/api/logs?kind=' + encodeURIComponent(kind));
      document.getElementById('logs').textContent = data.logs || '(aucun log)';
    }
    async function saveConfig() {
      const payload = {};
      for (const key of ['DISCORD_TOKEN','CLIENT_ID','GUILD_ID','CATEGORIE_DEFIS_ID','JARLBOT_MODE']) {
        const value = document.getElementById(key).value.trim();
        if (value) payload[key] = value;
      }
      await api('/api/config', { method: 'POST', body: JSON.stringify(payload) });
      setLast('Configuration sauvegardee.', 'ok');
      await loadStatus();
    }
    async function saveAndStart() {
      const payload = {};
      for (const key of ['DISCORD_TOKEN','CLIENT_ID','GUILD_ID','CATEGORIE_DEFIS_ID','JARLBOT_MODE']) {
        const value = document.getElementById(key).value.trim();
        if (value) payload[key] = value;
      }
      await api('/api/config', { method: 'POST', body: JSON.stringify(payload) });
      const r = await api('/api/bot/start', { method: 'POST' });
      setLast(r.message || 'Bot lance + slash commands enregistrees.', 'ok');
      await loadStatus();
      await loadLogs().catch(() => {});
    }
    async function stopLauncher() {
      try {
        // stop bot if running
        await api('/api/bot/stop', { method: 'POST' }).catch(() => {});
        // request launcher to exit
        await api('/api/launcher/stop', { method: 'POST' });
        setLast('Arrêt demandé. Le launcher va se fermer.', 'warn');
      } catch (err) {
        setLast('Erreur arrêt: ' + err.message, 'bad');
      }
    }
    loadStatus().catch(err => setLast(err.message, 'bad'));
    loadLogs().catch(() => {});
    setInterval(loadStatus, 5000);
    setInterval(loadLogs, 7000);
  </script>
</body>
</html>`;

async function handle(req, res) {
  try {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    if (req.method === 'GET' && url.pathname === '/') {
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(html);
      return;
    }
    if (req.method === 'GET' && url.pathname === '/api/status') {
      const env = readEnv();
      json(res, {
        env: {
          CLIENT_ID: env.CLIENT_ID || '',
          GUILD_ID: env.GUILD_ID || '',
          CATEGORIE_DEFIS_ID: env.CATEGORIE_DEFIS_ID || '',
          JARLBOT_MODE: env.JARLBOT_MODE || 'prod',
          DISCORD_TOKEN: mask(env.DISCORD_TOKEN),
        },
        botRunning: Boolean(botProcess && !botProcess.killed),
        refreshRunning: Boolean(refreshProcess && !refreshProcess.killed),
        db: getDbStatus(),
      });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/config') {
      const body = await readBody(req);
      writeEnv(body);
      json(res, { ok: true });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/bot/start') {
      json(res, startBot());
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/bot/stop') {
      json(res, stopBot());
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/refresh') {
      const body = await readBody(req);
      const result = startRefresh(body.mode || 'normal');
      json(res, { ...result, message: result.started ? `Refresh ${body.mode || 'normal'} lance.` : result.message });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/deploy') {
      if (deployProcess && !deployProcess.killed) {
        json(res, { ok: false, message: 'Enregistrement deja en cours.' });
        return;
      }
      deploySlashCommands();
      json(res, { ok: true, message: 'Enregistrement des commandes lance.' });
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/export') {
      const result = await runExport();
      json(res, result, result.code === 0 ? 200 : 500);
      return;
    }
    if (req.method === 'POST' && url.pathname === '/api/launcher/stop') {
      json(res, { ok: true, message: 'Arret du launcher demande.' });
      setTimeout(() => {
        try {
          server.close(() => {
            log('Launcher HTTP server ferme.');
            process.exit(0);
          });
        } catch (e) {
          log('Erreur lors de la fermeture du launcher: ' + (e && e.message));
          process.exit(0);
        }
      }, 300);
      return;
    }
    if (req.method === 'GET' && url.pathname === '/api/logs') {
      const kind = url.searchParams.get('kind') || 'bot';
      const file = kind === 'error' ? BOT_ERR_LOG : kind === 'refresh' ? REFRESH_LOG : kind === 'launcher' ? LAUNCHER_LOG : BOT_OUT_LOG;
      json(res, { logs: tail(file) });
      return;
    }
    json(res, { error: 'Route introuvable.' }, 404);
  } catch (err) {
    log(`Erreur launcher: ${err.stack || err.message}`);
    json(res, { error: err.message }, 500);
  }
}

const server = http.createServer((req, res) => {
  handle(req, res);
});

function listenOnAvailablePort(startPort, maxAttempts = 20) {
  const tryListen = (port, remainingAttempts) => {
    server.once('error', (err) => {
      if (err.code === 'EADDRINUSE' && remainingAttempts > 0) {
        log(`Port ${port} deja utilise, essai sur ${port + 1}.`);
        tryListen(port + 1, remainingAttempts - 1);
        return;
      }
      log(`Impossible de demarrer le launcher: ${err.message}`);
      process.exit(1);
    });

    server.listen(port, () => {
      const actualPort = server.address().port;
      const url = `http://localhost:${actualPort}`;
      log(`Launcher disponible sur ${url}`);
      if (process.env.JARLBOT_LAUNCHER_NO_OPEN !== '1') openBrowser(url);
    });
  };

  tryListen(startPort, maxAttempts);
}

listenOnAvailablePort(PORT);
